name: Docker build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Go Tests" ]
    branches:
      - master
      - develop
    types:
      - completed
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    name: Docker build
    runs-on: self-hosted-ubuntu-23.04
    services:
      # local registry
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Env
        run: echo "IMAGE_SUFFIXED=${{ !startsWith(github.ref, 'refs/tags/v') && '-dev' || ''  }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            localhost:5000/ecoblock-node${{ env.IMAGE_SUFFIXED }}
            ecoblocklabs/ecoblock-node${{ env.IMAGE_SUFFIXED }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build ecoblock-node image
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          target: nitro-node-default
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build ecoblock-node-dev image
        uses: docker/build-push-action@v2
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          target: nitro-node-dev
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Print WAVM module root
        id: module-root
        run: |
          # Unfortunately, `docker cp` seems to always result in a "permission denied"
          # We work around this by piping a tarball through stdout
          docker run --rm --entrypoint tar ${{ fromJSON(steps.meta.outputs.json).tags[0] }} -cf - target/machines | tar xf -
          module_root="$(cat "target/machines/latest/module-root.txt")"
          echo "::set-output name=module-root::$module_root"
          echo -e "\x1b[1;34mWAVM module root:\x1b[0m $module_root"

      - name: Upload WAVM machine as artifact
        uses: actions/upload-artifact@v3
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: wavm-machine-${{ steps.module-root.outputs.module-root }}
          path: target/machines/latest/*
          if-no-files-found: error

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          sudo rm -rf /tmp/.buildx-cache
          sudo mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Clear cache on failure
        if: failure()
        run: |
          keys=(${{ runner.os }}-buildx- ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }})
          for key in "${keys[@]}"; do
            curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/caches/$key"
          done
